spring:
  application:
    name: fault-tolerance-demo
management:
  endpoints:
    web:
      exposure:
        include: info,health,circuitbreakers
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    aspect-order: 2
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 3
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    aspect-order: 1
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 10ms
        retryExceptions:
          - java.lang.Exception
  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 2s